### ISSUE TITLE
Restart after ConsumerTooSlow error can cause database connection failure

### ISSUE THREAD

**Issue by emilyhunt** [bluesky-astronomy/astronomy-feeds#2]
We lost the firehose for about an hour today due to an error in the database connection that was caught, killing the worker.

```[firehose] [2023-10-30 09:59:01] INFO:server.data_filter:Added to astro-all: 1; astro: 0
[firehose] [2023-10-30 09:59:01] INFO:server.data_filter:Timing stats:
[firehose] [2023-10-30 09:59:01] opn: 16.841  del: 0.000 add: 10.247 clo: 0.245
[firehose] [2023-10-30 10:00:07] INFO:server.data_filter:Added to astro-all: 1; astro: 0
[firehose] [2023-10-30 10:00:07] INFO:server.data_filter:Timing stats:
[firehose] [2023-10-30 10:00:07] opn: 11.878  del: 0.001 add: 6.016 clo: 0.217
[firehose] [2023-10-30 10:00:09] INFO:server.data_filter:Added to astro-all: 1; astro: 0
[firehose] [2023-10-30 10:00:09] INFO:server.data_filter:Timing stats:
[firehose] [2023-10-30 10:00:09] opn: 13.252  del: 0.000 add: 8.743 clo: 0.261
[firehose] [2023-10-30 10:00:48] INFO:server.data_filter:Added to astro-all: 1; astro: 0
[firehose] [2023-10-30 10:00:48] INFO:server.data_filter:Timing stats:
[firehose] [2023-10-30 10:00:48] opn: 9.576  del: 0.001 add: 7.427 clo: 0.224
[firehose] [2023-10-30 10:00:54] INFO:server.data_filter:Added to astro-all: 1; astro: 0
[firehose] [2023-10-30 10:00:54] INFO:server.data_filter:Timing stats:
[firehose] [2023-10-30 10:00:54] opn: 10.664  del: 0.000 add: 23.842 clo: 0.182
[firehose] [2023-10-30 10:04:29] INFO:server.data_filter:Added to astro-all: 1; astro: 0
[firehose] [2023-10-30 10:04:29] INFO:server.data_filter:Timing stats:
[firehose] [2023-10-30 10:04:29] opn: 10.754  del: 0.000 add: 5.999 clo: 0.161
[firehose] [2023-10-30 10:16:05] WARNING:server.firehose:Reconnecting to Firehose due to ConsumerTooSlow...
[firehose] [2023-10-30 10:16:05] Running firehose for did:web:feed-all.astronomy.blue
[firehose] [2023-10-30 10:16:05] - worker process started
[firehose] [2023-10-30 10:16:05] Process Process-2:
[firehose] [2023-10-30 10:16:05] Traceback (most recent call last):
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3246, in execute_sql
[firehose] [2023-10-30 10:16:05]     cursor.execute(sql, params or ())
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
[firehose] [2023-10-30 10:16:05]     result = self._query(query)
[firehose] [2023-10-30 10:16:05]              ^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
[firehose] [2023-10-30 10:16:05]     conn.query(q)
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query
[firehose] [2023-10-30 10:16:05]     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
[firehose] [2023-10-30 10:16:05]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
[firehose] [2023-10-30 10:16:05]     result.read()
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read
[firehose] [2023-10-30 10:16:05]     first_packet = self.connection._read_packet()
[firehose] [2023-10-30 10:16:05]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/connections.py", line 739, in _read_packet
[firehose] [2023-10-30 10:16:05]     packet_header = self._read_bytes(4)
[firehose] [2023-10-30 10:16:05]                     ^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/connections.py", line 795, in _read_bytes
[firehose] [2023-10-30 10:16:05]     raise err.OperationalError(
[firehose] [2023-10-30 10:16:05] pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
[firehose] [2023-10-30 10:16:05] 
[firehose] [2023-10-30 10:16:05] During handling of the above exception, another exception occurred:
[firehose] [2023-10-30 10:16:05] 
[firehose] [2023-10-30 10:16:05] Traceback (most recent call last):
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
[firehose] [2023-10-30 10:16:05]     self.run()
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/multiprocessing/process.py", line 108, in run
[firehose] [2023-10-30 10:16:05]     self._target(*self._args, **self._kwargs)
[firehose] [2023-10-30 10:16:05]   File "/workspace/server/firehose.py", line 85, in worker_main
[firehose] [2023-10-30 10:16:05]     operations_callback(_get_ops_by_type(commit))
[firehose] [2023-10-30 10:16:05]   File "/workspace/server/data_filter.py", line 73, in operations_callback
[firehose] [2023-10-30 10:16:05]     valid_dids = account_list.get_accounts()
[firehose] [2023-10-30 10:16:05]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/server/accounts.py", line 39, in get_accounts
[firehose] [2023-10-30 10:16:05]     self.query_database()
[firehose] [2023-10-30 10:16:05]   File "/workspace/server/accounts.py", line 29, in query_database_with_closing
[firehose] [2023-10-30 10:16:05]     self.accounts = self.account_query()
[firehose] [2023-10-30 10:16:05]                     ^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/server/accounts.py", line 34, in account_query
[firehose] [2023-10-30 10:16:05]     return {account.did for account in Account.select()}
[firehose] [2023-10-30 10:16:05]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 7107, in __iter__
[firehose] [2023-10-30 10:16:05]     self.execute()
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 1966, in inner
[firehose] [2023-10-30 10:16:05]     return method(self, database, *args, **kwargs)
[firehose] [2023-10-30 10:16:05]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 2037, in execute
[firehose] [2023-10-30 10:16:05]     return self._execute(database)
[firehose] [2023-10-30 10:16:05]            ^^^^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 2210, in _execute
[firehose] [2023-10-30 10:16:05]     cursor = database.execute(self)
[firehose] [2023-10-30 10:16:05]              ^^^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3254, in execute
[firehose] [2023-10-30 10:16:05]     return self.execute_sql(sql, params)
[firehose] [2023-10-30 10:16:05]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3244, in execute_sql
[firehose] [2023-10-30 10:16:05]     with __exception_wrapper__:
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3014, in __exit__
[firehose] [2023-10-30 10:16:05]     reraise(new_type, new_type(exc_value, *exc_args), traceback)
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 192, in reraise
[firehose] [2023-10-30 10:16:05]     raise value.with_traceback(tb)
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/peewee.py", line 3246, in execute_sql
[firehose] [2023-10-30 10:16:05]     cursor.execute(sql, params or ())
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
[firehose] [2023-10-30 10:16:05]     result = self._query(query)
[firehose] [2023-10-30 10:16:05]              ^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
[firehose] [2023-10-30 10:16:05]     conn.query(q)
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query
[firehose] [2023-10-30 10:16:05]     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
[firehose] [2023-10-30 10:16:05]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
[firehose] [2023-10-30 10:16:05]     result.read()
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read
[firehose] [2023-10-30 10:16:05]     first_packet = self.connection._read_packet()
[firehose] [2023-10-30 10:16:05]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/connections.py", line 739, in _read_packet
[firehose] [2023-10-30 10:16:05]     packet_header = self._read_bytes(4)
[firehose] [2023-10-30 10:16:05]                     ^^^^^^^^^^^^^^^^^^^
[firehose] [2023-10-30 10:16:05]   File "/workspace/.heroku/python/lib/python3.11/site-packages/pymysql/connections.py", line 795, in _read_bytes
[firehose] [2023-10-30 10:16:05]     raise err.OperationalError(
[firehose] [2023-10-30 10:16:05] peewee.OperationalError: (2013, 'Lost connection to MySQL server during query')```

**Comment by emilyhunt** [comment]
The ConsumerTooSlow issue may be unrelated (e.g. the pipe to the worker may have reached a limit), I saw a case of this happening _without_ that error. All issues seem to be with the database losing connection.
